version: '3.8'
services: 
  react-app:
    build: ./client
    ports: 
      - 3000:3000
    volumes:
      - ./client:/client
    env_file: ./client/.env
  node:
    build: ./server
    ports:
      - 5000:5000
    env_file: ./server/.env
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - db
  db:
    container_name: pgContainer
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4Container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin